kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.todoapp.serviceAccount.name }}
  namespace: {{ .Values.todoapp.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.todoapp.serviceAccount.name }}
  namespace: {{ .Values.todoapp.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.todoapp.serviceAccount.name }}-binding
  namespace: {{ .Values.todoapp.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.todoapp.serviceAccount.name }}
  namespace: {{ .Values.todoapp.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.todoapp.serviceAccount.name }}
  apiGroup: rbac.authorization.k8s.io
